= Stndard Library Configの設定方法
:author: hituzi no sippo
:email: contact@hituzi-no-sippo.me
:revnumber: v1.1.0
:revdate: 2021-09-26T16:30:36+0900
:revremark: anyの使用時の注意を追加した
:doctype: article
:description: seleneのStndard Library Configの設定方法の説明
:title:
:experimental:
:showtitle:
:!sectnums:
:sectids:
:toc: preamble
:sectlinks:
:sectanchors:
:idprefix:
:idseparator: -
:xrefstyle: full
:!example-caption:
:!figure-caption:
:!table-caption:
:!listing-caption:
:copyright: Copyright (c) 2021 {author}

:first-publication-date: 2021-09-26T10:03:33+0900
:creation-date: 2021-09-25T09:43:19+0900

:copyright-with-author-link: Copyright (c) 2021 link:https://github.com/hituzi-no-sippo[{author}^]
:tags: [Lua, Lint, selene, Config]
:selene-stdlib-document-url: https://kampfkarren.github.io/selene/usage/std.html

// tag::body[]

.Official Documentation
link:{selene-stdlib-document-url}[
Standard Library Format - selene Documentation^]

stndard library(stdlib) configは、link:https://toml.io[TOML format^]で設定します。

[CAUTION]
====
seleneのconfig fileで、stdlib configの設定をしても、効果はありません。
stdlib configの設定を変更しません。
====

== [selene]

`selene` tableには、meta情報を書きます。

.Keys
base::
  baseとするstdlibを指定します。
  baseではなく、stdlib configの値を優先します。
name::
  stdlibの名前を指定します。
  `name = roblox` のとき、Robloxのlintを提供するなど、selene内部で使用します。
structs::
  Robloxなどで使用する構造体を定義します。

.Config
[source, TOML]
----
[selene]
base = 'lua51'
----

seleneに組みこまれているLua 5.1 or 5.2以外を `base` に使用する場合、
stdlib configのfile名を入力します。

.Config
[source, TOML]
----
[selene]
# `neovim.toml` のstdlib configをbaseにします
base = 'neovim'
# `selene/neovim.toml` のstdlib configをbaseにします
base = 'selene/neovim'

# 2つのstdlib configをbaseに使用する場合、 `+` を間に加えます
base = 'apple+banana'
----

[CAUTION]
====
`base = 'selene/neovim'` のとき
`selene/neovim.toml` を探す処理のcurrent directoryは
`base = 'selene/neovim'` を記載しているstdlib configのdirectoryになります。
`std = <std_config_file_name>` を記載している、
config fileのdirectoryではありません。
====

== Global

globalにproperty・関数を定義します。

tableの名前が、property・関数名になります。

.Config
[source, TOML]
----
# globalに `hoo` propertyを、定義します
[hoo]
property = true

# globalに `vim.o.number` を、propertyとして定義します
# 上書きを許可しているpropertyです。
[vim.o.number]
property  = true
writable = 'overridden'

# globalに `vim.lsp.buf.formatting` を、関数として定義します
# 関数の第1引数は、型がtableで、入力を省略できます。
[[vim.lsp.buf.formatting.args]]
type     = 'table'
required = false
----

=== Any

定義したものが、property・関数なんでもOKになります。

.Example
[source, TOML]
----
# `vim` を定義をします
[vim]
any = true
----

[literal]
....
# `vim` を `any` で定義する前
error[undefined_variable]: `vim` is not defined
  ┌─ test.lua:1:7
  │
1 │ print(vim)
  │       ^^^

error[undefined_variable]: `vim` is not defined
  ┌─ test.lua:2:7
  │
2 │ print(vim())
  │       ^^^

error[undefined_variable]: `vim` is not defined
  ┌─ test.lua:3:7
  │
3 │ print(vim.o.number)
  │       ^^^

error[undefined_variable]: `vim` is not defined
  ┌─ test.lua:4:7
  │
4 │ print(vim.opt.number:get())
  │       ^^^

Results:
4 errors
0 warnings
0 parse errors

# `vim` を `any` で定義した後
Results:
0 errors
0 warnings
0 parse errors
....

[CAUTION]
====
`any = true` のproperty配下のproperty・関数を定義しても、
定義した設定を反映しません。

.Code
[source, Lua]
----
vim.NIL = 123
vim.tbl_count()
----

.Config
[source, TOML]
----
[vim]
any = true

[vim.NIL]
property = true

[[vim.tbl_count.args]]
type = 'table'
----

.Rusult
[literal]
....
# `vim` を `any` で定義する前
error[incorrect_standard_library_use]: standard library function `vim.tbl_count` requires 1 parameters, 0 passed
  ┌─ test.lua:1:1
  │
1 │ vim.tbl_count()
  │ ^^^^^^^^^^^^^^^

error[incorrect_standard_library_use]: standard library global `vim.NIL` is not writable
  ┌─ test.lua:2:1
  │
2 │ vim.NIL = 123
  │ ^^^^^^^

Results:
2 errors
0 warnings
0 parse errors

# `vim` を `any` で定義した後
Results:
0 errors
0 warnings
0 parse errors
....
====

=== Table

`hoo` のfiled(e.g. `hoo.foo`)を定義するため
`hoo` の定義を記載する必要はありません。
`hoo` のfiledを定義すると、tableとして、自動的に `hoo` も定義します。

.Example
[source, TOML]
----
# 次の記載は必要ありません
# `print(hoo)` のようなcodeがあっても `hoo` は自動的に定義されるので
# errorは発生しません
# [hoo]
# property = true

[hoo.foo]
property = true
----

[literal]
....
# `hoo.foo` の定義を記載する前
error[undefined_variable]: `hoo` is not defined
  ┌─ test.lua:1:7
  │
1 │ print(hoo)
  │       ^^^

error[undefined_variable]: `hoo` is not defined
  ┌─ test.lua:2:7
  │
2 │ print(hoo.foo)
  │       ^^^

Results:
2 errors
0 warnings
0 parse errors

# `hoo.foo` の定義を記載した後
Results:
0 errors
0 warnings
0 parse errors
....

=== Property

include::./property.adoc[tags='body,!license', leveloffset=+3]

=== Function

include::./function.adoc[tags='body,!license', leveloffset=+3]

=== removed

baseのstdlib configから、指定のproperty・関数を削除します。

.Example
[source, TOML]
----
# `string` の定義をしている、lua 5.1のstdlibを使用します
[selene]
base = 'lua51'

# `string` の定義を削除します
[strign]
removed = true
----

[literal]
....
# `removed` で `string` の定義を削除する前
Results:
0 errors
0 warnings
0 parse errors

# `removed` で `string` の定義を削除した後
error[undefined_variable]: `string` is not defined
  ┌─ test.lua:1:7
  │
1 │ print(string)
  │       ^^^^^^

error[undefined_variable]: `string` is not defined
  ┌─ test.lua:2:7
  │
2 │ print(string.len('hoo'))
  │       ^^^^^^

Results:
2 errors
0 warnings
0 parse errors
....

=== Struct

構造体instaceのfieldを定義したいなら `struct` を使用します。

.Example
[source, TOML]
----
[game]
struct = 'StructName'
----

構造体instaceは、Robloxなどで使用します。
`[selene,structs]` で、構造体を定義します。

構造体の詳細は
link:{selene-stdlib-document-url}#structs[
official documentation^]を読んでください。

=== Wildcard

include::./wildcard.adoc[tags='body,!license', leveloffset=+3]

'''

// tag::license[]

:selene-license-link: link:https://github.com/Kampfkarren/selene/blob/main/LICENSE.md[selene LICENSE^]
.{selene-license-link}
[%collapsible%open]
=====

[literal]
....
Mozilla Public License Version 2.0
==================================

### 1. Definitions

**1.1. “Contributor”**
    means each individual or legal entity that creates, contributes to
    the creation of, or owns Covered Software.

**1.2. “Contributor Version”**
    means the combination of the Contributions of others (if any) used
    by a Contributor and that particular Contributor's Contribution.

**1.3. “Contribution”**
    means Covered Software of a particular Contributor.

**1.4. “Covered Software”**
    means Source Code Form to which the initial Contributor has attached
    the notice in Exhibit A, the Executable Form of such Source Code
    Form, and Modifications of such Source Code Form, in each case
    including portions thereof.

**1.5. “Incompatible With Secondary Licenses”**
    means

* **(a)** that the initial Contributor has attached the notice described
    in Exhibit B to the Covered Software; or
* **(b)** that the Covered Software was made available under the terms of
    version 1.1 or earlier of the License, but not also under the
    terms of a Secondary License.

**1.6. “Executable Form”**
    means any form of the work other than Source Code Form.

**1.7. “Larger Work”**
    means a work that combines Covered Software with other material, in
    a separate file or files, that is not Covered Software.

**1.8. “License”**
    means this document.

**1.9. “Licensable”**
    means having the right to grant, to the maximum extent possible,
    whether at the time of the initial grant or subsequently, any and
    all of the rights conveyed by this License.

**1.10. “Modifications”**
    means any of the following:

* **(a)** any file in Source Code Form that results from an addition to,
    deletion from, or modification of the contents of Covered
    Software; or
* **(b)** any new file in Source Code Form that contains any Covered
    Software.

**1.11. “Patent Claims” of a Contributor**
    means any patent claim(s), including without limitation, method,
    process, and apparatus claims, in any patent Licensable by such
    Contributor that would be infringed, but for the grant of the
    License, by the making, using, selling, offering for sale, having
    made, import, or transfer of either its Contributions or its
    Contributor Version.

**1.12. “Secondary License”**
    means either the GNU General Public License, Version 2.0, the GNU
    Lesser General Public License, Version 2.1, the GNU Affero General
    Public License, Version 3.0, or any later versions of those
    licenses.

**1.13. “Source Code Form”**
    means the form of the work preferred for making modifications.

**1.14. “You” (or “Your”)**
    means an individual or a legal entity exercising rights under this
    License. For legal entities, “You” includes any entity that
    controls, is controlled by, or is under common control with You. For
    purposes of this definition, “control” means **(a)** the power, direct
    or indirect, to cause the direction or management of such entity,
    whether by contract or otherwise, or **(b)** ownership of more than
    fifty percent (50%) of the outstanding shares or beneficial
    ownership of such entity.


### 2. License Grants and Conditions

#### 2.1. Grants

Each Contributor hereby grants You a world-wide, royalty-free,
non-exclusive license:

* **(a)** under intellectual property rights (other than patent or trademark)
    Licensable by such Contributor to use, reproduce, make available,
    modify, display, perform, distribute, and otherwise exploit its
    Contributions, either on an unmodified basis, with Modifications, or
    as part of a Larger Work; and
* **(b)** under Patent Claims of such Contributor to make, use, sell, offer
    for sale, have made, import, and otherwise transfer either its
    Contributions or its Contributor Version.

#### 2.2. Effective Date

The licenses granted in Section 2.1 with respect to any Contribution
become effective for each Contribution on the date the Contributor first
distributes such Contribution.

#### 2.3. Limitations on Grant Scope

The licenses granted in this Section 2 are the only rights granted under
this License. No additional rights or licenses will be implied from the
distribution or licensing of Covered Software under this License.
Notwithstanding Section 2.1(b) above, no patent license is granted by a
Contributor:

* **(a)** for any code that a Contributor has removed from Covered Software;
    or
* **(b)** for infringements caused by: **(i)** Your and any other third party's
    modifications of Covered Software, or **(ii)** the combination of its
    Contributions with other software (except as part of its Contributor
    Version); or
* **(c)** under Patent Claims infringed by Covered Software in the absence of
    its Contributions.

This License does not grant any rights in the trademarks, service marks,
or logos of any Contributor (except as may be necessary to comply with
the notice requirements in Section 3.4).

#### 2.4. Subsequent Licenses

No Contributor makes additional grants as a result of Your choice to
distribute the Covered Software under a subsequent version of this
License (see Section 10.2) or under the terms of a Secondary License (if
permitted under the terms of Section 3.3).

#### 2.5. Representation

Each Contributor represents that the Contributor believes its
Contributions are its original creation(s) or it has sufficient rights
to grant the rights to its Contributions conveyed by this License.

#### 2.6. Fair Use

This License is not intended to limit any rights You have under
applicable copyright doctrines of fair use, fair dealing, or other
equivalents.

#### 2.7. Conditions

Sections 3.1, 3.2, 3.3, and 3.4 are conditions of the licenses granted
in Section 2.1.


### 3. Responsibilities

#### 3.1. Distribution of Source Form

All distribution of Covered Software in Source Code Form, including any
Modifications that You create or to which You contribute, must be under
the terms of this License. You must inform recipients that the Source
Code Form of the Covered Software is governed by the terms of this
License, and how they can obtain a copy of this License. You may not
attempt to alter or restrict the recipients' rights in the Source Code
Form.

#### 3.2. Distribution of Executable Form

If You distribute Covered Software in Executable Form then:

* **(a)** such Covered Software must also be made available in Source Code
    Form, as described in Section 3.1, and You must inform recipients of
    the Executable Form how they can obtain a copy of such Source Code
    Form by reasonable means in a timely manner, at a charge no more
    than the cost of distribution to the recipient; and

* **(b)** You may distribute such Executable Form under the terms of this
    License, or sublicense it under different terms, provided that the
    license for the Executable Form does not attempt to limit or alter
    the recipients' rights in the Source Code Form under this License.

#### 3.3. Distribution of a Larger Work

You may create and distribute a Larger Work under terms of Your choice,
provided that You also comply with the requirements of this License for
the Covered Software. If the Larger Work is a combination of Covered
Software with a work governed by one or more Secondary Licenses, and the
Covered Software is not Incompatible With Secondary Licenses, this
License permits You to additionally distribute such Covered Software
under the terms of such Secondary License(s), so that the recipient of
the Larger Work may, at their option, further distribute the Covered
Software under the terms of either this License or such Secondary
License(s).

#### 3.4. Notices

You may not remove or alter the substance of any license notices
(including copyright notices, patent notices, disclaimers of warranty,
or limitations of liability) contained within the Source Code Form of
the Covered Software, except that You may alter any license notices to
the extent required to remedy known factual inaccuracies.

#### 3.5. Application of Additional Terms

You may choose to offer, and to charge a fee for, warranty, support,
indemnity or liability obligations to one or more recipients of Covered
Software. However, You may do so only on Your own behalf, and not on
behalf of any Contributor. You must make it absolutely clear that any
such warranty, support, indemnity, or liability obligation is offered by
You alone, and You hereby agree to indemnify every Contributor for any
liability incurred by such Contributor as a result of warranty, support,
indemnity or liability terms You offer. You may include additional
disclaimers of warranty and limitations of liability specific to any
jurisdiction.


### 4. Inability to Comply Due to Statute or Regulation

If it is impossible for You to comply with any of the terms of this
License with respect to some or all of the Covered Software due to
statute, judicial order, or regulation then You must: **(a)** comply with
the terms of this License to the maximum extent possible; and **(b)**
describe the limitations and the code they affect. Such description must
be placed in a text file included with all distributions of the Covered
Software under this License. Except to the extent prohibited by statute
or regulation, such description must be sufficiently detailed for a
recipient of ordinary skill to be able to understand it.


### 5. Termination

**5.1.** The rights granted under this License will terminate automatically
if You fail to comply with any of its terms. However, if You become
compliant, then the rights granted under this License from a particular
Contributor are reinstated **(a)** provisionally, unless and until such
Contributor explicitly and finally terminates Your grants, and **(b)** on an
ongoing basis, if such Contributor fails to notify You of the
non-compliance by some reasonable means prior to 60 days after You have
come back into compliance. Moreover, Your grants from a particular
Contributor are reinstated on an ongoing basis if such Contributor
notifies You of the non-compliance by some reasonable means, this is the
first time You have received notice of non-compliance with this License
from such Contributor, and You become compliant prior to 30 days after
Your receipt of the notice.

**5.2.** If You initiate litigation against any entity by asserting a patent
infringement claim (excluding declaratory judgment actions,
counter-claims, and cross-claims) alleging that a Contributor Version
directly or indirectly infringes any patent, then the rights granted to
You by any and all Contributors for the Covered Software under Section
2.1 of this License shall terminate.

**5.3.** In the event of termination under Sections 5.1 or 5.2 above, all
end user license agreements (excluding distributors and resellers) which
have been validly granted by You or Your distributors under this License
prior to termination shall survive termination.


### 6. Disclaimer of Warranty

> Covered Software is provided under this License on an “as is”
> basis, without warranty of any kind, either expressed, implied, or
> statutory, including, without limitation, warranties that the
> Covered Software is free of defects, merchantable, fit for a
> particular purpose or non-infringing. The entire risk as to the
> quality and performance of the Covered Software is with You.
> Should any Covered Software prove defective in any respect, You
> (not any Contributor) assume the cost of any necessary servicing,
> repair, or correction. This disclaimer of warranty constitutes an
> essential part of this License. No use of any Covered Software is
> authorized under this License except under this disclaimer.

### 7. Limitation of Liability

> Under no circumstances and under no legal theory, whether tort
> (including negligence), contract, or otherwise, shall any
> Contributor, or anyone who distributes Covered Software as
> permitted above, be liable to You for any direct, indirect,
> special, incidental, or consequential damages of any character
> including, without limitation, damages for lost profits, loss of
> goodwill, work stoppage, computer failure or malfunction, or any
> and all other commercial damages or losses, even if such party
> shall have been informed of the possibility of such damages. This
> limitation of liability shall not apply to liability for death or
> personal injury resulting from such party's negligence to the
> extent applicable law prohibits such limitation. Some
> jurisdictions do not allow the exclusion or limitation of
> incidental or consequential damages, so this exclusion and
> limitation may not apply to You.


### 8. Litigation

Any litigation relating to this License may be brought only in the
courts of a jurisdiction where the defendant maintains its principal
place of business and such litigation shall be governed by laws of that
jurisdiction, without reference to its conflict-of-law provisions.
Nothing in this Section shall prevent a party's ability to bring
cross-claims or counter-claims.


### 9. Miscellaneous

This License represents the complete agreement concerning the subject
matter hereof. If any provision of this License is held to be
unenforceable, such provision shall be reformed only to the extent
necessary to make it enforceable. Any law or regulation which provides
that the language of a contract shall be construed against the drafter
shall not be used to construe this License against a Contributor.


### 10. Versions of the License

#### 10.1. New Versions

Mozilla Foundation is the license steward. Except as provided in Section
10.3, no one other than the license steward has the right to modify or
publish new versions of this License. Each version will be given a
distinguishing version number.

#### 10.2. Effect of New Versions

You may distribute the Covered Software under the terms of the version
of the License under which You originally received the Covered Software,
or under the terms of any subsequent version published by the license
steward.

#### 10.3. Modified Versions

If you create software not governed by this License, and you want to
create a new license for such software, you may create and use a
modified version of this License if you rename the license and remove
any references to the name of the license steward (except to note that
such modified license differs from this License).

#### 10.4. Distributing Source Code Form that is Incompatible With Secondary Licenses

If You choose to distribute Source Code Form that is Incompatible With
Secondary Licenses under the terms of this version of the License, the
notice described in Exhibit B of this License must be attached.

## Exhibit A - Source Code Form License Notice

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.

If it is not possible or desirable to put the notice in a particular
file, then You may include the notice in a location (such as a LICENSE
file in a relevant directory) where a recipient would be likely to look
for such a notice.

You may add additional accurate notices of copyright ownership.

## Exhibit B - “Incompatible With Secondary Licenses” Notice

    This Source Code Form is "Incompatible With Secondary Licenses", as
    defined by the Mozilla Public License, v. 2.0.


....

=====

// end::license[]

// end::body[]


// tag::copyright[]

'''

{copyright-with-author-link}

// end::copyright[]
