= Taplo
:author: hituzi no sippo
:email: contact@hituzi-no-sippo.me
:revnumber: v1.0.0
:revdate:
:revremark: First Edition
:doctype: article
:description: linter・formatterでもあるTOML toolkit
:title:
:experimental:
:showtitle:
:!sectnums:
:sectids:
:toc: preamble
:sectlinks:
:sectanchors:
:idprefix:
:idseparator: -
:xrefstyle: full
:!example-caption:
:!figure-caption:
:!table-caption:
:!listing-caption:
:copyright: Copyright (c) 2021 {author}

:first-publication-date:
:creation-date: 2021-09-27T08:12:16+0900

:copyright-with-author-link: Copyright (c) 2021 link:https://github.com/hituzi-no-sippo[{author}^]
:tags: [TOML, Taplo, Lint, Formatter, Validator, CLI]
:taplo-url: https://taplo.tamasfe.dev/

.Official Documentation
link:{taplo-url}[Taplo — A TOML Toolkit^]

link:{taplo-url}[Taplo^]は、linetrやformatterにもなるTOMLのtoolkitです。

.Taploの特徴
* TOML fileのformatter
* TOML fileのlinter +
  link:https://json-schema.org/[
  JSON Schema^]を使用して、validationもできます。
* link:https://github.com/toml-lang/toml/releases/tag/1.0.0[
  TOML v1.0^]に対応している

link:{taplo-url}/lsp/[LSP^]とlink:https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml[
VSCodeの拡張機能^]もあります。

この記事ではlibraryの説明をしません。CLIやConfigの説明をします。

'''

// tag::license[]

:taplo-license-link: link:https://github.com/tamasfe/taplo/blob/master/LICENSE.md[Taplo LICENSE^]
.{taplo-license-link}
[%collapsible%open]
=====

[literal]
....
MIT License

Copyright (c) 2020 Ferenc Tamás

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
....

=====

// end::license[]


// tag::copyright[]

'''

{copyright-with-author-link}

// end::copyright[]
